main:

  - title: "Comparative Analysis of Southern Blot and qPCR Telomere Length Measurements through Comprehensive Statistical Approaches"
    authors: Mendez, K. J. W.*, <strong>Lee, S. K.*</strong>, Dagnall, C., Lai, T.-P., Katki, H., Spellman, S. R., Stewart, V., Aviv, A., Gadalla, S. M.<sup>&#9993;</sup>, and Hong, H. G.<sup>&#9993;</sup> 
    conference: GeroScience (2026)

  - title: "Identification and Validation of Poly-Metabolite Scores for Diets High in Ultra-Processed Food: An Observational Study and Post-Hoc Randomized Controlled Crossover-Feeding Trial"
    authors: Abar, L., Steele, E. M., <strong>Lee, S. K.</strong>, Kahle, L., Moore, S. C., Watts, E., Matthews, C., Herrick, K., Hall, K. D., Oâ€™Connor, L. E., Freedman, N. D., Sinha, R., Hong, H. G., and Loftfield, E.<sup>&#9993;</sup> 
    conference: PLOS Medicine (2025)
    paper: https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1004560

  - title: "Superficial X-ray in the treatment of nonaggressive basal and squamous cell carcinoma in the elderly: A 22-year retrospective analysis"
    authors: Mattia, A., Thompson, A., <strong>Lee, S. K.</strong>, Hong, H. G., Green, W. H.<sup>&#9993;</sup>, and Cognetta Jr, A. B. 
    conference: Journal of the American Academy of Dermatology (2024)
    paper: https://www.jaad.org/article/S0190-9622(24)00069-0/fulltext

